### ISSUE TITLE
更新10.15了吗？

### ISSUE THREAD

**Issue by huangguaba** [qzz0518/hackintosh_9400f_b360_vega56#1]
更新10.15了吗？

**Comment by Zerah64** [comment]
因为是工作机，我暂时没有升级 10.15，等过段时间稳定点了我会再升级 10.15；但是我已经把 clover 更新到最新版本了，看论坛里面的大部分反馈 10.14 的 EFI 在更新到最新的 clover 之后都是可以直升 10.15 的，你可以用懒人包做好 15 的安装盘，安装后替换 EFI 试一试，如果有问题的话可以参考别人的 9400f 相关 EFI。

**Comment by qzz0518** [comment]
> 更新10.15了吗？

因为是工作机，我暂时没有升级 10.15，等过段时间稳定点了我会再升级 10.15；但是我已经把 clover 更新到最新版本了，看论坛里面的大部分反馈 10.14 的 EFI 在更新到最新的 clover 之后都是可以直升 10.15 的，你可以用懒人包做好 15 的安装盘，安装后替换 EFI 试一试，如果有问题的话可以参考别人的 9400f 相关 EFI。
