### ISSUE TITLE
安装黑屏

### ISSUE THREAD

**Issue by cctomato** [qzz0518/hackintosh_9400f_b360_vega56#10]
您好，我的cpu和主板和您的配置一样的。但我的显卡是RX580 2048sp的，已经刷了RX570的bios。所以直接用了您的clover配置。安装的时候第一步很正常，能够进入界面正常安装，等到安装完成第二步应该进入系统初次使用进行设置的时候就黑屏了，显示器无信号，但机器还在运转。我用的是10.15.4的系统，HDMI输出的。在远景爬文也无果，想麻烦您帮我看看会是什么原因造成的。

**Comment by qzz0518** [comment]
1. 可以开 clover 的啰嗦模式看下开机的错误代码，然后搜索对应错误
2. 可以试试换 dp 线连接显示器

**Comment by likeb** [comment]
黑屏问题应在HDMI，用DP接口。

**Comment by cctomato** [comment]
> * 可以开 clover 的啰嗦模式看下开机的错误代码，然后搜索对应错误
> * 可以试试换 dp 线连接显示器

是我刷显卡bios刷错了，导致显卡无法被识别。现在已经好了，感谢您的config

**Comment by cctomato** [comment]
> 黑屏问题应在HDMI，用DP接口。

是显卡bios刷错了，导致显卡无法被识别。
