### ISSUE TITLE
显卡 rx 560xt 

### ISSUE THREAD

**Issue by leaicc** [qzz0518/hackintosh_9400f_b360_vega56#11]
你好，我的主板和 CPU 跟你的一样，显卡是rx 560xt，也是免驱的，需要修改 EFI 文件吗？

**Comment by qzz0518** [comment]
免驱的话不需要修改

**Comment by leaicc** [comment]
好的，谢谢。我刚开始安装，第一步就出现了问题，四叶草界面不显示安装盘。只有一个 windows 盘，你有遇到过吗？

**Comment by leaicc** [comment]
已解决，EFI/CLOVER/drivers/UEFI 缺少了 HFSPlus.efi 文件，加入就 ok 了
