### ISSUE TITLE
请问能支持13.6版本的系统吗？

### ISSUE THREAD

**Issue by keer6** [qzz0518/hackintosh_9400f_b360_vega56#12]
如题

**Comment by qzz0518** [comment]
只测试过 10.14 和 10.15 ，10.13 你可以尝试一下，不保证能用

**Comment by keer6** [comment]
> 只测试过 10.14 和 10.15 ，10.13 你可以尝试一下，不保证能用

大佬都在玩高版本的了，找了半天没有找到合适的10.13
