### ISSUE TITLE
请问iphone通过pd快充线(usb-c to lightning)连接电脑  算是usb-c 2.0设备吗

### ISSUE THREAD

**Issue by liuzhili1994** [qzz0518/hackintosh_9400f_b360_vega56#14]
如题，我双系统，iphone通过快充线连接黑苹果，电脑不识别，但是我进入windows系统就可以连接。是不是因为大佬屏蔽了后置usb-c接口  usb2.0设备连接 的原因？我的配置除了显卡是580，其他的都一样。我电脑没有wifi，只能通过这个办法连接iphone，麻烦大佬解答一下

**Comment by qzz0518** [comment]
算，主板后面那个c口的usb2.0我没做适配，只能连3.0以上的，你要用手机联网，换普通的lightning线也可以联

**Comment by liuzhili1994** [comment]
嗯嗯，知道了，谢谢。我自己折腾去了

**Comment by liuzhili1994** [comment]
大佬，更新了最新的efi，发现睡眠之后时间会静止，比如1：00进入睡眠，1：30接触睡眠进入系统，时间停在1点零几分，网上说是主板电池的问题，但是我用windows睡眠就没有问题，麻烦大佬测试一下有没有这个问题？

**Comment by qzz0518** [comment]
确实有这个问题，这个问题应该是为了修复 10.15.4 重启重置 bios，加入了RTCMemoryFixup.kext 引起的，我找时间看怎么修复下

**Comment by qzz0518** [comment]
> 大佬，更新了最新的efi，发现睡眠之后时间会静止，比如1：00进入睡眠，1：30接触睡眠进入系统，时间停在1点零几分，网上说是主板电池的问题，但是我用windows睡眠就没有问题，麻烦大佬测试一下有没有这个问题？

换了一种方式解决 bios 重置的问题，删除了RTCMemoryFixup及启动参数，现在测试睡眠没问题了

**Comment by liuzhili1994** [comment]
> > 大佬，更新了最新的efi，发现睡眠之后时间会静止，比如1：00进入睡眠，1：30接触睡眠进入系统，时间停在1点零几分，网上说是主板电池的问题，但是我用windows睡眠就没有问题，麻烦大佬测试一下有没有这个问题？
> 
> 换了一种方式解决 bios 重置的问题，删除了RTCMemoryFixup及启动参数，现在测试睡眠没问题了
大佬辛苦了，有一个小小的请求，就是以后更新的时候，能不能把config.plist文件的修改细节也公布出来？毕竟其他文件可以直接覆盖，config里还有自己自定义的内容
