### ISSUE TITLE
B360M主板上有一个4针的上面标了usb9的usb插孔不能用

### ISSUE THREAD

**Issue by bigzhanghy** [qzz0518/hackintosh_9400f_b360_vega56#15]
我是接了蓝牙的供电线的，接在这4针口上，在clover还可以使用。一进mac就无法识别了。

**Comment by qzz0518** [comment]
4 针的 usb2.0 吗，我的蓝牙也是接在这上面的，但是可用；你可以配合黑果小兵的 usb 定制，去适配下主板的内置 usb2.0 口
