### ISSUE TITLE
您好  网卡您用的什么型号的

### ISSUE THREAD

**Issue by Hsintao** [qzz0518/hackintosh_9400f_b360_vega56#2]
RT

**Comment by qzz0518** [comment]
> RT

主板上的有线网卡是免驱的，无线网卡是 **BCM94360** ，tb 你搜索 **黑苹果BCM94360** 就有了，买带有免驱蓝牙的就行

**Comment by Hsintao** [comment]
> > RT
> 
> 主板上的有线网卡是免驱的，无线网卡是 **BCM94360** ，tb 你搜索 **黑苹果BCM94360** 就有了，买带有免驱蓝牙的就行

谢谢

**Comment by Hsintao** [comment]
> > RT
> 
> 主板上的有线网卡是免驱的，无线网卡是 **BCM94360** ，tb 你搜索 **黑苹果BCM94360** 就有了，买带有免驱蓝牙的就行

再打扰您一下，安装NGFF转M2转接板后的长度能安装在主板上吗 我看商家介绍都说比标准的m2无线网卡长几公分

**Comment by qzz0518** [comment]
> > > RT
> > 
> > 
> > 主板上的有线网卡是免驱的，无线网卡是 **BCM94360** ，tb 你搜索 **黑苹果BCM94360** 就有了，买带有免驱蓝牙的就行
> 
> 再打扰您一下，安装NGFF转M2转接板后的长度能安装在主板上吗 我看商家介绍都说比标准的m2无线网卡长几公分

这个你得问问店家，我网卡是买的 PCIE 接口的无线网卡，蓝牙和网卡集成在一起的那种，需要占用一个 PCIE 槽和一个主板 USB2.0 针

**Comment by Hsintao** [comment]
> 网

好的 谢谢
