### ISSUE TITLE
麻烦您，请教个问题，配置如下，用了咱们的efi，正常安装，驱动正常，关机后，再开机，进入系统后，5分钟内自动重启。

### ISSUE THREAD

**Issue by ttylshui** [qzz0518/hackintosh_9400f_b360_vega56#20]
麻烦您，请教个问题，配置如下，用了咱们的efi，正常安装，驱动正常，关机后，再开机，进入系统后，5分钟内自动重启。再进入问题依旧。新手，不明白还需要调什么，配置如下。能看出问题或告诉我到哪里能找到问题的解决方案吗？或相关的知识需要补充点啥吗？现在一团乱麻。谢谢。

电脑型号	X64 兼容 台式电脑
操作系统	Windows 10 Enterprise 64位 ( DirectX 12 )
	
处理器	英特尔 Core i7-9700 @ 3.00GHz 八核
主板	华硕 TUF B360M-PLUS GAMING S ( B360 芯片组 )
内存	16 GB ( 金士顿 DDR4 2666MHz )
主硬盘	三星 MZVLB512HAJQ-00000 ( 512 GB / 固态硬盘 )
显卡	AMD Radeon RX 590 Series ( 8 GB / 迪兰 )
显示器	TFT2360 DVI ( 23.6 英寸  )
声卡	瑞昱 ALC887 @ 英特尔 High Definition Audio 控制器
网卡	英特尔 Ethernet Connection  I219-V / 华硕

**Comment by qzz0518** [comment]
这个问题我没有遇到过，还是需要您自己来分析。
参考如下 bios 设置看下你的 bios 是否设置正确。
![bios 设置](https://i.loli.net/2020/05/04/r652gXdpctjasJK.png)
