### ISSUE TITLE
使用 i7-9700 （无k 无f）卡顿

### ISSUE THREAD

**Issue by vanishcode** [qzz0518/hackintosh_9400f_b360_vega56#25]
首先感谢，用了一天上午就吃上了黑苹果🍎，不过发现在使用过程中存在卡顿的现象（比如开启Chrome就会一卡一卡的），而且cpu风扇一直处于跑满的状态，但cpu占用率并不高。

会和ssd和显卡型号有关吗？还是显卡（核显 or 独显）驱动的问题？

ssd 读写速度大概在 450mb/s

显卡型号为rx560

**Comment by qzz0518** [comment]
有核显的 cpu 可能会不兼容，你可以参考下这个配置
http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1855391&highlight=tuf

**Comment by vanishcode** [comment]
> 有核显的 cpu 可能会不兼容，你可以参考下这个配置
> http://bbs.pcbeta.com/forum.php?mod=viewthread&tid=1855391&highlight=tuf

感谢回复～ 🌹 我晚上回去用其他电脑的 9100f 排查一下是否是核显问题

**Comment by vanishcode** [comment]
刚换了9100f，目前没有卡顿的现象了；cpu风扇没加，温度值也正常了，之前一直99度98度，现在70-80多度。猜测之前使用的是核显独显虽然识别但是没有生效。十分感谢～ @qzz0518
