### ISSUE TITLE
准备换个显卡

### ISSUE THREAD

**Issue by wanbing0610** [qzz0518/hackintosh_9400f_b360_vega56#26]
要买一样的显卡才能成功吗？

**Comment by qzz0518** [comment]
所有免驱的 A 卡均可，受支持的 A 卡见如下网页。
[可驱动的显卡](https://heipg.cn/tutorial/graphic-card-for-macos-2020.html)

**Comment by wanbing0610** [comment]
显卡为蓝宝石rx5500xt，efi文件替换后，屏幕颜色失真，是我efi替换有问题？

| |
wanbing0610
|
|
邮箱：wanbing0610@163.com
|

Signature is customized by Netease Mail Master

在2020年07月09日 22:17，Zerah 写道：

所有免驱的 A 卡均可，受支持的 A 卡见如下网页。
可驱动的显卡

**Comment by qzz0518** [comment]
您看下是否开启了 HDR ，在显示器设置中关闭”高动态范围即可“

**Comment by wanbing0610** [comment]
不知道啥问题，换了之后，efi引导选项都没有了！




| |
wanbing0610
|
|
邮箱：wanbing0610@163.com
|

Signature is customized by Netease Mail Master

在2020年07月20日 09:35，Zerah 写道：

您看下是否开启了 HDR ，在显示器设置中关闭”高动态范围即可“

**Comment by wanbing0610** [comment]
先忽略吧！除了颜色失真，install form mac catlina这个启动项也没有！我是把您的efi的目录和同目录下的boot.efi文件，替换掉u盘里面的对应的文件！也许是我操作不当，今天回去再试试！
| |
wanbing0610
|
|
邮箱：wanbing0610@163.com
|

Signature is customized by Netease Mail Master

在2020年07月20日 09:35，Zerah 写道：

您看下是否开启了 HDR ，在显示器设置中关闭”高动态范围即可“
