### ISSUE TITLE
您好，您用TUF B360M PLUS S + INTEL I3 I5核显安装过吗？

### ISSUE THREAD

**Issue by likeb** [qzz0518/hackintosh_9400f_b360_vega56#3]
我同款TUF B360主板 CPU是 I3 9100 核显安装 用你的EFI 不卡代码但 一直黑屏 
不过尽管黑屏  系统安装程序应正常运行 只是视频输出应默认是DP而非 HDMI 如何解决输出问题？
我看很多教程是安装后用HACKINTOOLS更改输出  本人小白 望指教安装前如何操作 先谢谢！

**Comment by qzz0518** [comment]
你好，我没有用有核显的CPU 安装过。但是核显的话，你可以先使用黑果小兵的通用 EFI 安装系统正常驱动核显，安装后再通过 config 对比，把我发布的 EFI 的 kext 和 USB 定制文件拷贝过去 。如果你已经安装成功了修改核显输出的话，得参考下教程 [核显修改教程](https://blog.daliansky.net/Tutorial-Using-Hackintool-to-open-the-correct-pose-of-the-8th-generation-core-display-HDMI-or-DVI-output.html)

**Comment by likeb** [comment]
小兵的系统我安装同样黑屏，他发布最新的镜像说明中已经支持8代UHD630，可我的9代I3不行，难道是8代UHD630和9代UHD630有区别的原因？
还有一种办法就是买显卡安装。谢谢耐心解答。
