### ISSUE TITLE
你好，我用同样的主板，安装卡在PCI Configuration End是怎么回事呢？

### ISSUE THREAD

**Issue by irblei** [qzz0518/hackintosh_9400f_b360_vega56#4]
配置是9600k 5700xt

**Comment by qzz0518** [comment]
建议使用懒人包直接进行安装，在安装前需要再 BIOS 里面进行一些设置（关闭一些东西，你可以网上搜一搜，都是通用的），然后成功之后再替换我发布的 EFI 
[懒人包下载地址和安装教程](https://blog.daliansky.net/macOS-Catalina-10.15.2-19C57-Release-version-with-Clover-5100-original-image-Double-EFI-Version.html)
最新的懒人包安装大部分都是没什么问题的
