### ISSUE TITLE
谢谢大佬分享的efi，请问下大佬可以分享下你用的黑果的无线网卡的型号或者链接么？

### ISSUE THREAD

**Issue by heistrock** [qzz0518/hackintosh_9400f_b360_vega56#5]
谢谢大佬分享的efi，使用了两天，继续使用中，打算当作主力机器使用，笔记本性能太差了，所以搞了个黑果来用，打算加个无线网卡，之前黑果小冰的10.15.2的版本安装不成功，进入不了系统，换成了10.15的版本，直接装好替换EFI，基本完美体验。
但是9400F的变频测试只有两个频率，有点奇怪，2.9和3.9(反正一个基频一个睿频)的，但是我看IPG的显示，频率是有正常动态变化的，不知道是不是个例的问题。
总之一切都好，现在还不打算升级到10.15.2，当做工作用机，怕出问题
大佬看看能不能分享你的黑果的无线网卡的型号，带蓝牙的吧？我也打算入手一个

**Comment by qzz0518** [comment]
CPU 频率这个一般都不会有什么问题的，不用管他。
[链接](https://item.taobao.com/item.htm?spm=a1z09.2.0.0.18ff2e8dElIgGe&id=569121658326&_u=c22hc8uqc1d6)
我买的 185 双天线这款，貌似他现在涨价了，你可以找找有没有更便宜的，这款 win10 和 macOS 都正常使用。

**Comment by heistrock** [comment]
好的，谢谢大佬！
对了大佬，我使用过程中，有出现自动重启的问题，使用了3天，出现了两次，我起初以为是睡眠，不知道你那边有没有出现过这个问题呢？我自己也还在排查，这个概率比较低，不知道什么原因造成的。

**Comment by qzz0518** [comment]
我这儿暂时没出现重启的现象，EFI 里面 kext 都是最新的，如果重启频繁的话，你可以试下把系统直升到 最新版本看是否有改善。

**Comment by heistrock** [comment]
好的，谢谢大佬的回复，我会使用下再评估
