### ISSUE TITLE
我也是943602cs网卡，但蓝牙接在4针的usb上10.15.3不识别，10.14.6可以识别

### ISSUE THREAD

**Issue by sweetdali** [qzz0518/hackintosh_9400f_b360_vega56#7]

**Comment by qzz0518** [comment]
一般 pcie 的943602cs黑苹果网卡都是集成一个免驱的 usb 蓝牙，比如我的蓝牙是BRCM20702，这个在苹果系统是免驱的，目前在我电脑上没有问题。你可以在你的 USB 总线看到你的 USB 蓝牙型号，然后搜索对症解决就行。
